CREATE SCHEMA MILTANKBANK;

CREATE SEQUENCE MILTANKBANK.ID_RECEITA_SEQ;

CREATE TABLE MILTANKBANK.RECEITA (
    ID_RECEITA INTEGER NOT NULL DEFAULT NEXTVAL ('MILTANKBANK.ID_RECEITA_SEQ'),
    DESCRICAO_RECEITA CHARACTER VARYING(100) NOT NULL,
    VALOR_RECEITA NUMERIC(10,2) NOT NULL,
    DATA_RECEITA DATE NOT NULL,
    PRIMARY KEY (ID_RECEITA)    
);

CREATE SEQUENCE MILTANKBANK.ID_CATEGORIA_SEQ;

CREATE TABLE MILTANKBANK.CATEGORIA (
    ID_CATEGORIA INTEGER NOT NULL DEFAULT NEXTVAL ('MILTANKBANK.ID_CATEGORIA_SEQ'),
    DESCRICAO_CATEGORIA CHARACTER VARYING(11) NOT NULL,
    PRIMARY KEY (ID_CATEGORIA)
);


CREATE SEQUENCE MILTANKBANK.ID_DESPESA_SEQ;

CREATE TABLE MILTANKBANK.DESPESA (
    ID_DESPESA INTEGER NOT NULL DEFAULT NEXTVAL ('MILTANKBANK.ID_DESPESA_SEQ'),
    DESCRICAO_DESPESA CHARACTER VARYING(100) NOT NULL,
    VALOR_DESPESA NUMERIC(10,2) NOT NULL,
    DATA_DESPESA DATE NOT NULL,
    ID_CATEGORIA INTEGER,
    PRIMARY KEY (ID_DESPESA),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES MILTANKBANK.CATEGORIA(ID_CATEGORIA)
);

INSERT INTO 
    MILTANKBANK.CATEGORIA (DESCRICAO_CATEGORIA)
VALUES
    ('Alimentação'),
    ('Saúde'),
    ('Moradia'),
    ('Transporte'),
    ('Educação'),
    ('Lazer'),
    ('Imprevistos'),
    ('Outras');

DELETE FROM MILTANKBANK.DESPESA;

ALTER SEQUENCE MILTANKBANK.ID_DESPESA_SEQ RESTART 1;

DELETE FROM MILTANKBANK.RECEITA;

ALTER SEQUENCE MILTANKBANK.ID_RECEITA_SEQ RESTART 1;