server:
  servlet:
    context-path: /miltankbank
spring:
  application:
    name: miltankbank
  datasource:
    url: jdbc:postgresql://localhost:5436/db_miltankbank
    username: miltankbank_web
    password: 13052001
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

miltankbank: 
  jwt:
    secret: rm'!@N=Ke!~p8VTA2ZRK~nMDQX5Uvm!m'D&]{@Vr?G;2?XhbC:Qa#9#eMLN\}x3?JR3.2zr~v)gYF^8\:8>:XfB:Ww75N/emt9Yj[bQMNCWwW\J?N,nvH.<2\.r~w]*e~vgak)X"v8H`MH/7"2E`,^k@n<vE-wD3g9JWPy;CrY*.Kd2_D])=><D?YhBaSua5hW%{2]_FVXzb9`8FH^b[X3jzVER&:jw2<=c38=>L/zBq`}C6tT*cCSVC^c]-L}&/
    expiration: 86400000