CREATE SCHEMA MILTANKBANK;

CREATE SEQUENCE MILTANKBANK.ID_RECEITA_SEQ;

CREATE TABLE MILTANKBANK.RECEITA (
    ID_RECEITA INTEGER NOT NULL DEFAULT NEXTVAL ('MILTANKBANK.ID_RECEITA_SEQ'),
    DESCRICAO_RECEITA CHARACTER VARYING(100) NOT NULL,
    VALOR_RECEITA NUMERIC(10,2) NOT NULL,
    DATA_RECEITA DATE NOT NULL,
    PRIMARY KEY (ID_RECEITA)    
);

CREATE SEQUENCE MILTANKBANK.ID_CATEGORIA_SEQ;

CREATE TABLE MILTANKBANK.CATEGORIA (
    ID_CATEGORIA INTEGER NOT NULL DEFAULT NEXTVAL ('MILTANKBANK.ID_CATEGORIA_SEQ'),
    DESCRICAO_CATEGORIA CHARACTER VARYING(11) NOT NULL,
    PRIMARY KEY (ID_CATEGORIA)
);


CREATE SEQUENCE MILTANKBANK.ID_DESPESA_SEQ;

CREATE TABLE MILTANKBANK.DESPESA (
    ID_DESPESA INTEGER NOT NULL DEFAULT NEXTVAL ('MILTANKBANK.ID_DESPESA_SEQ'),
    DESCRICAO_DESPESA CHARACTER VARYING(100) NOT NULL,
    VALOR_DESPESA NUMERIC(10,2) NOT NULL,
    DATA_DESPESA DATE NOT NULL,
    ID_CATEGORIA INTEGER,
    PRIMARY KEY (ID_DESPESA),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES MILTANKBANK.CATEGORIA(ID_CATEGORIA)
);

INSERT INTO 
    MILTANKBANK.CATEGORIA (DESCRICAO_CATEGORIA)
VALUES
    ('Alimentação'),
    ('Saúde'),
    ('Moradia'),
    ('Transporte'),
    ('Educação'),
    ('Lazer'),
    ('Imprevistos'),
    ('Outras');

CREATE SEQUENCE MILTANKBANK.ID_PERFIL_SEQ;

CREATE TABLE MILTANKBANK.PERFIL (
    ID_PERFIL INTEGER NOT NULL DEFAULT NEXTVAL ('MILTANKBANK.ID_PERFIL_SEQ'),
    NOME_PERFIL CHARACTER VARYING (40) NOT NULL,
    PRIMARY KEY (ID_PERFIL)
);

INSERT INTO 
    MILTANKBANK.PERFIL(NOME_PERFIL)
VALUES 
    ('Usuario');

CREATE SEQUENCE MILTANKBANK.ID_USUARIO_SEQ;

CREATE TABLE MILTANKBANK.USUARIO (
    ID_USUARIO INTEGER NOT NULL DEFAULT NEXTVAL ('MILTANKBANK.ID_USUARIO_SEQ'),
    NOME_COMPLETO_USUARIO CHARACTER VARYING(100) NOT NULL,
    NOME_USUARIO CHARACTER VARYING (40) NOT NULL,
    SENHA CHARACTER VARYING (80) NOT NULL,
    PRIMARY KEY (ID_USUARIO)
);

INSERT INTO 
    MILTANKBANK.USUARIO (NOME_COMPLETO_USUARIO, NOME_USUARIO, SENHA)
VALUES
    ('Ash Ketchum', 'ashKetchum', '$2a$10$dffDlUNltFXFXMGIavbEdObE79L654tVFT99DYIlr2QcWljVt8hJy');

CREATE TABLE MILTANKBANK.USUARIO_PERFIS (
    ID_USUARIO INTEGER NOT NULL,
    ID_PERFIL INTEGER NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_PERFIL),
    FOREIGN KEY (ID_USUARIO) REFERENCES MILTANKBANK.USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_PERFIL) REFERENCES MILTANKBANK.PERFIL(ID_PERFIL)
);

INSERT INTO
    MILTANKBANK.USUARIO_PERFIS(ID_USUARIO, ID_PERFIL)
VALUES
    ('1','1');

DELETE FROM MILTANKBANK.DESPESA;

ALTER SEQUENCE MILTANKBANK.ID_DESPESA_SEQ RESTART 1;

DELETE FROM MILTANKBANK.RECEITA;

ALTER SEQUENCE MILTANKBANK.ID_RECEITA_SEQ RESTART 1;